name: mingw-w64 build
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: windows-latest
    env:
      MSYSTEM: MINGW64
      MSYS2_PATH_TYPE: inherit
      CC: ccache gcc
      CXX: ccache g++
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Setup ccache dir
        run: Write-Output "::set-env name=CCACHE_DIR::$PWD/.ccache"

      - name: Cache ccache
        id: cache-msys64
        uses: actions/cache@v2
        with:
          path: .ccache
          key: ${{ runner.os }}-msys64-${{ hashFiles('**/*.c') }}
          restore-keys: ${{ runner.os }}-msys64-

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: autoconf make automake-wrapper libtool mingw-w64-x86_64-ccache mingw-w64-x86_64-gcc
          update: true

      - name: Run autoreconf
        shell: msys2 {0}
        run: autoreconf -fiv

      - name: Run Configure
        shell: msys2 {0}
        run: ./configure --prefix=/mingw64

      - name: Run make
        shell: msys2 {0}
        run: make -j4 install

      - name: Print ccache info and clean pacman
        shell: msys2 {0}
        run: |
          ccache -s
          pacman -Sc --noconfirm
